name: Docker Image CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      # 1. Check out o código do repositório
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Configurar Docker para executar ações
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # 3. Fazer login no Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}  # Armazene o nome de usuário no segredo
          password: ${{ secrets.DOCKER_PASSWORD }}  # Armazene a senha no segredo

      # 4. Construir a imagem Docker
      - name: Build Docker image
        run: |
          docker build -t myusername/myapp:${{ github.sha }} .

      # 5. Executar os testes dentro do container Docker
      - name: Run tests in Docker container
        run: |
          docker run --rm myusername/myapp:${{ github.sha }} python -m unittest discover

      # 6. Publicar a imagem no Docker Hub
      - name: Push Docker image to Docker Hub
        run: |
          docker push myusername/myapp:${{ github.sha }}
